# Generated by Django 5.2.6 on 2025-10-21 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Herramienta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionHerramienta',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_id', models.PositiveIntegerField(help_text='ID de la tarea de mantenimiento')),
                ('tarea_descripcion', models.CharField(blank=True, help_text='Descripción breve de la tarea', max_length=255)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='herramientas.herramienta')),
            ],
            options={
                'db_table': 'AsignacionHerramienta',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
