# Generated by Django 5.2.6 on 2025-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En uso'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
    ]
