# Generated by Django 5.2.6 on 2025-10-28 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BACKUP', 'Backup generado'), ('RESTORE', 'Restauración aplicada'), ('UPLOAD', 'Respaldo subido'), ('DOWNLOAD', 'Respaldo descargado')], max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
