# Generated by Django 5.2.6 on 2025-11-11 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
        ('mantenimiento', '0001_initial'),
        ('plantas', '0003_alter_plantaarbol_fecha_plantacion_and_more'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tareamantenimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('herramienta', 'fecha_programada'), name='uniq_herramienta_fecha_pendiente', violation_error_message='La herramienta ya está asignada en ese horario.'),
        ),
    ]
