# Generated by Django 5.2.6 on 2025-11-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_tareamantenimiento_uniq_herramienta_fecha_pendiente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tareamantenimiento',
            name='uniq_herramienta_fecha_pendiente',
        ),
    ]
