# Generated by Django 5.2.6 on 2025-11-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_remove_tareamantenimiento_uniq_herramienta_fecha_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='recordatorio_24h_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
