# Generated by Django 5.2.6 on 2025-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_tareamantenimiento_recordatorio_24h_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='vencimiento_notificado',
            field=models.BooleanField(default=False),
        ),
    ]
