# Generated by Django 5.2.6 on 2025-10-28 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaludRegistro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha actualización')),
                ('estado_salud', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], db_index=True, default='verde', max_length=8, verbose_name='Estado de salud')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_salud', to='plantas.plantaarbol', verbose_name='Planta/Árbol')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_salud', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'SaludRegistro',
                'ordering': ['-fecha_actualizacion', '-id_registro'],
                'indexes': [models.Index(fields=['planta', 'fecha_actualizacion'], name='SaludRegist_planta__82fb0a_idx'), models.Index(fields=['estado_salud'], name='SaludRegist_estado__f83fae_idx')],
            },
        ),
    ]
