# Generated by Django 5.2.6 on 2025-10-29 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
        ('salud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaludHistorial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('estado_salud', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], max_length=8)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_salud', to='plantas.plantaarbol')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SaludHistorial',
                'ordering': ['-fecha_evento', '-id_historial'],
            },
        ),
    ]
