# Generated by Django 5.2.6 on 2025-11-14 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_alter_plantaarbol_fecha_plantacion_and_more'),
        ('salud', '0002_saludhistorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='saludregistro',
            name='estado_salud',
            field=models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], db_index=True, default='verde', max_length=8),
        ),
        migrations.AlterField(
            model_name='saludregistro',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='saludregistro',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='saludregistro',
            name='planta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_salud', to='plantas.plantaarbol', verbose_name='Planta/Árbol'),
        ),
        migrations.AlterField(
            model_name='saludregistro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_salud', to=settings.AUTH_USER_MODEL),
        ),
    ]
