# Generated by Django 5.2.6 on 2025-10-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_voluntario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('tipo_participacion', models.CharField(choices=[('estudiante', 'Estudiante'), ('trabajador', 'Trabajador'), ('externo', 'Voluntario externo')], default='estudiante', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Voluntario',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionVoluntario',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_id', models.PositiveIntegerField(help_text='ID de la tarea/actividad')),
                ('actividad', models.CharField(blank=True, help_text='Descripción corta de la actividad', max_length=150)),
                ('evento_id', models.PositiveIntegerField(blank=True, help_text='ID del evento (opcional)', null=True)),
                ('evento_nombre', models.CharField(blank=True, max_length=150)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='voluntarios.voluntario')),
            ],
            options={
                'db_table': 'AsignacionVoluntario',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
