# Generated by Django 5.2.6 on 2025-09-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgeneral',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chatprivado',
            options={'managed': False},
        ),
    ]
