# Generated by Django 5.2.6 on 2025-10-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionProducto',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_id', models.PositiveIntegerField(help_text='ID de la tarea de mantenimiento')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='productos.producto')),
            ],
            options={
                'db_table': 'AsignacionProducto',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id_existencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='existencia', to='productos.producto')),
            ],
            options={
                'db_table': 'Existencia',
            },
        ),
    ]
