# Generated by Django 5.2.6 on 2025-09-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plantaArbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('nombre_cientifico', models.CharField(max_length=100, verbose_name='NombreCientífico')),
                ('fecha_plantacion', models.DateTimeField(verbose_name='FechaPlantación')),
                ('imagen_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='ImagenURL')),
                ('periodicidad_riego', models.IntegerField(verbose_name='PeriodicidadRiego')),
                ('periodicidad_poda', models.IntegerField(verbose_name='PeriodicidadPoda')),
                ('periodicidad_fumigacion', models.IntegerField(verbose_name='PeriodicidadFumigación')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('id_ubicacion', models.IntegerField(verbose_name='IDUbicación')),
            ],
        ),
    ]
