# Generated by Django 5.2.6 on 2025-09-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plantaArbol',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(verbose_name="NombreComun", max_length=50, null=False)),
                ('nombre_cientifico', models.CharField(max_length=100, verbose_name='NombreCientífico')),
                ('descripcion', models.CharField(verbose_name="Descripción", max_length=600, null=False)),
                ('fecha_plantacion', models.DateField(null=True, verbose_name='FechaPlantación')),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to='plantas/%Y/%m/')),
                ('periodicidad_riego', models.IntegerField(verbose_name='PeriodicidadRiego')),
                ('periodicidad_poda', models.IntegerField(verbose_name='PeriodicidadPoda')),
                ('periodicidad_fumigacion', models.IntegerField(verbose_name='PeriodicidadFumigación')),
                ('lat', models.FloatField(null=True, verbose_name='Latitud')),
                ('lng', models.FloatField(null=True, verbose_name='Longitud')),
            ],
            options={
                'db_table': 'PlantaArbol',
            },
        ),
    ]
