# Generated by Django 5.2.6 on 2025-09-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plantaArbol',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('nombre_cientifico', models.CharField(max_length=100, verbose_name='NombreCientífico')),
                ('fecha_plantacion', models.DateField(null=True, verbose_name='FechaPlantación')),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to='plantas/%Y/%m/')),
                ('periodicidad_riego', models.IntegerField(verbose_name='PeriodicidadRiego')),
                ('periodicidad_poda', models.IntegerField(verbose_name='PeriodicidadPoda')),
                ('periodicidad_fumigacion', models.IntegerField(verbose_name='PeriodicidadFumigación')),
                ('descripcion_ubicacion', models.CharField(max_length=200, null=True, verbose_name='Descripcion ubicacion')),
                ('procedencia', models.CharField(max_length=200, null=True, verbose_name='Procedencia')),
                ('fecha_llegada', models.DateField(null=True, verbose_name='Fecha llegada')),
                ('lat', models.FloatField(null=True, verbose_name='Latitud')),
                ('lng', models.FloatField(null=True, verbose_name='Longitud')),
            ],
            options={
                'db_table': 'PlantaArbol',
            },
        ),
    ]
