# Generated by Django 5.2.6 on 2025-11-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantaarbol',
            name='periodicidad_fumigacion',
            field=models.CharField(max_length=40, verbose_name='PeriodicidadFumigación'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='periodicidad_poda',
            field=models.CharField(max_length=40, verbose_name='PeriodicidadPoda'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='periodicidad_riego',
            field=models.CharField(max_length=40, verbose_name='PeriodicidadRiego'),
        ),
    ]
