# Generated by Django 5.2.6 on 2025-09-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantaarbol',
            name='fecha_plantacion',
        ),
        migrations.RemoveField(
            model_name='plantaarbol',
            name='id_ubicacion',
        ),
        migrations.RemoveField(
            model_name='plantaarbol',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='plantaarbol',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='plantaarbol',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='plantaarbol',
            name='periodicidad_fumigacion',
        ),
        migrations.RemoveField(
            model_name='plantaarbol',
            name='periodicidad_poda',
        ),
        migrations.RemoveField(
            model_name='plantaarbol',
            name='periodicidad_riego',
        ),
    ]
