# Generated by Django 5.2.6 on 2025-11-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_alter_plantaarbol_periodicidad_fumigacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantaarbol',
            name='fecha_plantacion',
            field=models.DateField(null=True, verbose_name='Fecha Plantación'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='plantas/%Y/%m/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='nombre_cientifico',
            field=models.CharField(max_length=100, verbose_name='Nombre Científico'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='nombre_comun',
            field=models.CharField(max_length=50, verbose_name='Nombre Comun'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='periodicidad_fumigacion',
            field=models.CharField(max_length=40, verbose_name='Periodicidad Fumigación'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='periodicidad_poda',
            field=models.CharField(max_length=40, verbose_name='Periodicidad Poda'),
        ),
        migrations.AlterField(
            model_name='plantaarbol',
            name='periodicidad_riego',
            field=models.CharField(max_length=40, verbose_name='Periodicidad Riego'),
        ),
    ]
