# Generated by Django 5.2.6 on 2025-09-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_remove_plantaarbol_fecha_plantacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantaarbol',
            options={'managed': False},
        ),
    ]
