# Generated by Django 5.2.6 on 2025-09-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_alter_plantaarbol_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantaarbol',
            table='PlantaArbol',
        ),
    ]
