# Generated by Django 5.2.6 on 2025-10-25 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='incidenciaAmbiental',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('fecha_reporte', models.DateTimeField(verbose_name='FechaReporte')),
                ('area_campus', models.CharField(max_length=100, verbose_name='ÁreaCampus')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='pendiente', max_length=40, verbose_name='Estado')),
                ('id_planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plantas.plantaarbol', verbose_name='IDÁrbol')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='IDUsuario')),
            ],
        ),
    ]
